wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700317442.925453
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.8
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
